import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { useRouter } from "next/router";
import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";
import "./normalize.css";
import HydrationZustand from "./components/HydrationZustand";

const inter = Inter({
  weight: ["100", "200", "300", "400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HydrationZustand>
          <Navbar />
          {children}
          <Footer />
        </HydrationZustand>
      </body>
    </html>
  );
}
